"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-03 12:16:55.450796+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=400), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('restaurant', sa.String(length=120), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('per_100g', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('serving_g', sa.Float(), nullable=True),
    sa.Column('serving_desc', sa.String(length=120), nullable=True),
    sa.Column('source', sa.Enum('label', 'off', 'usda', 'web', 'model', 'user', name='item_source', native_enum=False, length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_index('ix_foods_barcode', ['barcode'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'onboarding', 'active', 'paused', 'deleted', name='user_status', native_enum=False, length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invite_code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('conversation_turns',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='turn_role', native_enum=False, length=32), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.create_index('ix_turns_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('days',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('card_message_id', sa.BigInteger(), nullable=True),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_days_user_date')
    )
    op.create_table('integrations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Enum('whoop', 'withings', 'apple_health', name='provider', native_enum=False, length=32), nullable=False),
    sa.Column('external_user_id', sa.String(length=128), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'connected', 'expired', 'revoked', 'error', name='integration_status', native_enum=False, length=32), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webhook_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_integrations_user_provider'),
    sa.UniqueConstraint('webhook_token')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index('ix_integrations_provider_external', ['provider', 'external_user_id'], unique=False)

    op.create_table('invites',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_by', sa.BigInteger(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('labs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('taken_at', sa.Date(), nullable=False),
    sa.Column('marker', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('ref_low', sa.Float(), nullable=True),
    sa.Column('ref_high', sa.Float(), nullable=True),
    sa.Column('flag', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('raw_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.create_index('ix_labs_user_taken', ['user_id', 'taken_at'], unique=False)

    op.create_table('meals',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('day_date', sa.Date(), nullable=False),
    sa.Column('slot', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', 'unknown', name='meal_slot', native_enum=False, length=32), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eaten_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('photo', 'text', 'voice', 'imported', 'planned', 'forwarded', name='meal_source', native_enum=False, length=32), nullable=False),
    sa.Column('raw_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index('ix_meals_user_day', ['user_id', 'day_date'], unique=False)
        batch_op.create_index('ix_meals_user_logged', ['user_id', 'logged_at'], unique=False)

    op.create_table('measurements',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('weight', 'waist', 'bodyfat', 'bp_sys', 'bp_dia', 'steps', 'rhr', 'hrv', 'other', name='measurement_type', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.create_index('ix_measurements_user_type_at', ['user_id', 'type', 'measured_at'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('preference', 'pattern', 'health', 'rule', 'event', 'answer', 'commitment', name='note_kind', native_enum=False, length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_turn_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['superseded_by'], ['notes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index('ix_notes_user_active', ['user_id', 'active'], unique=False)

    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Enum('whoop', 'withings', 'apple_health', name='provider', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state')
    )
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.create_index('ix_oauth_states_user', ['user_id'], unique=False)

    op.create_table('proactive_sends',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('window_key', sa.String(length=96), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_turn_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proactive_sends', schema=None) as batch_op:
        batch_op.create_index('ix_proactive_user_sent', ['user_id', 'sent_at'], unique=False)
        batch_op.create_index('ix_proactive_user_window', ['user_id', 'window_key'], unique=False)

    op.create_table('profiles',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('goal_text', sa.Text(), nullable=True),
    sa.Column('primary_kpi', sa.Enum('waist', 'weight', 'bodyfat', 'performance', name='primary_kpi', native_enum=False, length=32), nullable=True),
    sa.Column('kpi_target_low', sa.Float(), nullable=True),
    sa.Column('kpi_target_high', sa.Float(), nullable=True),
    sa.Column('kpi_unit', sa.String(length=16), nullable=True),
    sa.Column('wake_time', sa.Time(), nullable=True),
    sa.Column('bed_time', sa.Time(), nullable=True),
    sa.Column('work_pattern', sa.Text(), nullable=True),
    sa.Column('training_plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('meal_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('wearable', sa.String(length=64), nullable=True),
    sa.Column('likes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('dislikes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('allergies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('dietary_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('alcohol', sa.Text(), nullable=True),
    sa.Column('sweet_tooth', sa.Text(), nullable=True),
    sa.Column('comfort_food', sa.Text(), nullable=True),
    sa.Column('health_context', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('coaching_intensity', sa.Enum('gentle', 'direct', 'pushy', 'drill_sergeant', name='coaching_intensity', native_enum=False, length=32), nullable=False),
    sa.Column('explanation_level', sa.Enum('short', 'full', name='explanation_level', native_enum=False, length=32), nullable=False),
    sa.Column('proactive_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_start', sa.Time(), nullable=False),
    sa.Column('quiet_end', sa.Time(), nullable=False),
    sa.Column('checkin_times', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('temp_intensity', sa.Enum('gentle', 'direct', 'pushy', 'drill_sergeant', name='coaching_intensity', native_enum=False, length=32), nullable=True),
    sa.Column('temp_intensity_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('onboarding_done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waist_cadence_days', sa.Integer(), nullable=False),
    sa.Column('weight_cadence_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('protocols',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocols', schema=None) as batch_op:
        batch_op.create_index('ix_protocols_user_active', ['user_id', 'active'], unique=False)

    op.create_table('recoveries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Enum('whoop', 'screenshot', 'manual', 'apple_health', 'other', name='data_source', native_enum=False, length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rhr', sa.Float(), nullable=True),
    sa.Column('hrv_ms', sa.Float(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('skin_temp_c', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'external_id', name='uq_recoveries_external')
    )
    with op.batch_alter_table('recoveries', schema=None) as batch_op:
        batch_op.create_index('ix_recoveries_user_date', ['user_id', 'date'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'cancelled', name='reminder_status', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index('ix_reminders_user_status_due', ['user_id', 'status', 'due_at'], unique=False)

    op.create_table('sleep',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Enum('whoop', 'screenshot', 'manual', 'apple_health', 'other', name='data_source', native_enum=False, length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('in_bed_min', sa.Float(), nullable=True),
    sa.Column('asleep_min', sa.Float(), nullable=True),
    sa.Column('performance_pct', sa.Float(), nullable=True),
    sa.Column('stages_min', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('respiratory_rate', sa.Float(), nullable=True),
    sa.Column('disturbances', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'external_id', name='uq_sleep_external')
    )
    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.create_index('ix_sleep_user_started', ['user_id', 'started_at'], unique=False)

    op.create_table('summaries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('day', 'week', name='summary_kind', native_enum=False, length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'period_start', name='uq_summaries_period')
    )
    op.create_table('token_usage',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.Enum('turn', 'verify', 'proactive', 'summary', 'research', 'transcribe', name='usage_purpose', native_enum=False, length=32), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_read_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_write_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'model', 'purpose', name='uq_token_usage_key')
    )
    op.create_table('workouts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Enum('whoop', 'screenshot', 'manual', 'apple_health', 'other', name='data_source', native_enum=False, length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('sport', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('strain', sa.Float(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('zones_min', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'external_id', name='uq_workouts_external')
    )
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index('ix_workouts_user_started', ['user_id', 'started_at'], unique=False)

    op.create_table('meal_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('restaurant', sa.String(length=120), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('grams', sa.Float(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('alcohol_g', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('label', 'off', 'usda', 'web', 'model', 'user', name='item_source', native_enum=False, length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('countable', sa.Boolean(), nullable=False),
    sa.Column('model_estimate', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('user_correction', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_items', schema=None) as batch_op:
        batch_op.create_index('ix_meal_items_user_meal', ['user_id', 'meal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_items', schema=None) as batch_op:
        batch_op.drop_index('ix_meal_items_user_meal')

    op.drop_table('meal_items')
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index('ix_workouts_user_started')

    op.drop_table('workouts')
    op.drop_table('token_usage')
    op.drop_table('summaries')
    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.drop_index('ix_sleep_user_started')

    op.drop_table('sleep')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index('ix_reminders_user_status_due')

    op.drop_table('reminders')
    with op.batch_alter_table('recoveries', schema=None) as batch_op:
        batch_op.drop_index('ix_recoveries_user_date')

    op.drop_table('recoveries')
    with op.batch_alter_table('protocols', schema=None) as batch_op:
        batch_op.drop_index('ix_protocols_user_active')

    op.drop_table('protocols')
    op.drop_table('profiles')
    with op.batch_alter_table('proactive_sends', schema=None) as batch_op:
        batch_op.drop_index('ix_proactive_user_window')
        batch_op.drop_index('ix_proactive_user_sent')

    op.drop_table('proactive_sends')
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.drop_index('ix_oauth_states_user')

    op.drop_table('oauth_states')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index('ix_notes_user_active')

    op.drop_table('notes')
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_index('ix_measurements_user_type_at')

    op.drop_table('measurements')
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index('ix_meals_user_logged')
        batch_op.drop_index('ix_meals_user_day')

    op.drop_table('meals')
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_index('ix_labs_user_taken')

    op.drop_table('labs')
    op.drop_table('invites')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index('ix_integrations_provider_external')

    op.drop_table('integrations')
    op.drop_table('days')
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.drop_index('ix_turns_user_created')

    op.drop_table('conversation_turns')
    op.drop_table('users')
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_index('ix_foods_barcode')

    op.drop_table('foods')
    # ### end Alembic commands ###
